pub const DEFAULT_AGENT_CARDS: &[(&str, &str)] = &[
    (
        "mind_hunter.intake.md",
        include_str!("agents/mind_hunter.intake.md"),
    ),
    (
        "planner.task_graph.md",
        include_str!("agents/planner.task_graph.md"),
    ),
    (
        "executor.supervisor.md",
        include_str!("agents/executor.supervisor.md"),
    ),
    (
        "seeker.web_research.md",
        include_str!("agents/seeker.web_research.md"),
    ),
    (
        "processor.data.md",
        include_str!("agents/processor.data.md"),
    ),
    ("analyzer.data.md", include_str!("agents/analyzer.data.md")),
    (
        "algorithm.method.md",
        include_str!("agents/algorithm.method.md"),
    ),
    (
        "programmer.code.md",
        include_str!("agents/programmer.code.md"),
    ),
    (
        "debugger.error.md",
        include_str!("agents/debugger.error.md"),
    ),
    (
        "painter.visualization.md",
        include_str!("agents/painter.visualization.md"),
    ),
    (
        "reporter.final.md",
        include_str!("agents/reporter.final.md"),
    ),
    (
        "biologist.domain.md",
        include_str!("agents/biologist.domain.md"),
    ),
    (
        "reviewer.verifier.md",
        include_str!("agents/reviewer.verifier.md"),
    ),
    (
        "creator.capability_refactorer.md",
        include_str!("agents/creator.capability_refactorer.md"),
    ),
];
